### ISSUE TITLE
DHS Domains to be removed from DAP

### ISSUE THREAD

**Issue by mtharmon20** [18F/pulse#660]
Morning -

The following DHS domains do not have publicly accessible landing pages and DHS has determined they are not eligible for DAP due to privacy and security reasons:

cpnireporting.gov
nmsc.gov

Can these please be removed from the Pulse dashboard?  Thanks!

Matt

**Comment by tdlowden** [comment]
Added these to the "ineligible" list for PR #662

**Comment by gbinal** [comment]
I've merged #662.  These changes should take effect in the next scan (early next week).

**Comment by mtharmon20** [comment]
Any update on this - these two domains are still appearing in the DAP listing for DHS.

**Comment by tdlowden** [comment]
Hey all. It seems the scan has not taken the updated "not eligible" list into account. Can we revisit?

**Comment by konklone** [comment]
@tdlowden @gbinal I think it's because this hasn't been merged/deployed yet: https://github.com/18F/pulse/pull/661

I'm merging and deploying it now, and updating the scan server with the latest code directly. That should update the ineligible domains for the next scan.
